version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install --save-dev @angular-devkit/build-angular
      - npm install -g @angular/cli@8.3.9
  build:
    commands:
      - ng build --prod
  post_build:
    commands:
      - aws s3 sync dist/ s3://github-example-s3 
artifacts:
  type: zip
  base-directory: dist
  files:
    - '**/*'
